implementation 'com.squareup.okhttp3:okhttp:3.2.0'

        implementation 'com.jcodecraeer:xrecyclerview:1.5.9'

        implementation('com.github.bumptech.glide:glide:4.8.0') {
        exclude group: "com.android.support"
        }
        implementation 'com.jakewharton:disklrucache:2.0.2'

        implementation 'com.jakewharton:butterknife:8.4.0'
        annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'
        //动态权限
        implementation 'pub.devrel:easypermissions:2.0.0'

        implementation 'com.squareup.retrofit2:retrofit:2.5.0'
        implementation 'com.squareup.retrofit2:converter-gson:2.1.0'

        implementation 'org.greenrobot:greendao:3.2.0'
        implementation 'org.greenrobot:greendao-generator:3.2.0'

        implementation 'com.facebook.stetho:stetho:1.5.0'

        implementation 'io.reactivex.rxjava2:rxjava:2.0.1'
        implementation 'io.reactivex.rxjava2:rxandroid:2.0.1'


		 implementation 'org.greenrobot:eventbus:3.1.1'