package com.example.demo214.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.demo214.T1348647909107Bean;

import com.example.demo214.dao.T1348647909107BeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig t1348647909107BeanDaoConfig;

    private final T1348647909107BeanDao t1348647909107BeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        t1348647909107BeanDaoConfig = daoConfigMap.get(T1348647909107BeanDao.class).clone();
        t1348647909107BeanDaoConfig.initIdentityScope(type);

        t1348647909107BeanDao = new T1348647909107BeanDao(t1348647909107BeanDaoConfig, this);

        registerDao(T1348647909107Bean.class, t1348647909107BeanDao);
    }
    
    public void clear() {
        t1348647909107BeanDaoConfig.clearIdentityScope();
    }

    public T1348647909107BeanDao getT1348647909107BeanDao() {
        return t1348647909107BeanDao;
    }

}
